name: Jesper Kjeldgaard

url: 'https://thejspr.com'

description: 'Thejspr'

keywords: 'software engineer, systems engineer, full stack developer, freelance software developer, software entrepreneur'

permalink: 'blog/:title/'

markdown: kramdown

include: ['_headers']
exclude: ['Gemfile', 'Gemfile.lock', 'bin']

sass:
  style: compressed
  load_paths:
    - _sass
    - node_modules

plugins:
  - jekyll-sitemap
